### ISSUE TITLE
Border of water looks unnatural

### ISSUE THREAD

**Issue by yuvallevy** [KyuuGryphon/HiddenRealms#23]
This is next to the adventure "Waterlogged". The grass simply changes into water and the sea doesn't seem to have any depth.
![wahr1](https://cloud.githubusercontent.com/assets/8183897/9261322/bd503790-4215-11e5-8a28-7c3df3ffdcb2.png)

**Comment by KyuuGryphon** [comment]
Changed grass/dirt transition location - can't do much about the visual lack of depth, that seems to be an engine limitation
