### ISSUE TITLE
Redundant Wasteland Chasm Dialog

### ISSUE THREAD

**Issue by jdl96** [KyuuGryphon/HiddenRealms#25]
If you go to Wonderfalls and get the purple shard before even going to the Wastelands, this dialog still appears: http://i.imgur.com/HhrFafw.png
I suggest doing a command 2 for the GCs to be deactivated once you complete the adventure "A Link To The Future" or maybe make another interchange and use command 22 to point the dialog to it.

**Comment by KyuuGryphon** [comment]
Fixed
