### ISSUE TITLE
Recharging Brr in "Below Freezing"

### ISSUE THREAD

**Issue by Yzfm** [KyuuGryphon/HiddenRealms#29]
Pretty sure that this is unintentional: after recharging Brr for the first time, you can use it to make a way back to the charger by freezing the water around it, allowing you to recharge and enter the yellow gate area with your Brr already charged, so the faint chargers will be useless.

Again, I can send a screenshot/video if necessary...

**Comment by KyuuGryphon** [comment]
Fixed
